package Telas;

import coffee_machine.Conexao;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author etec
 */
public class Coffee_Machine_Tela extends javax.swing.JFrame {

    /**
     * Creates new form Coffe_Machine_Tela
     */
    public Coffee_Machine_Tela() {
        initComponents();
    }

    Conexao conn=new Conexao();
    double total=0;
    Image img[]= new Image[9];
    Double preco[]=new Double[9];
    int x = 0;
    int y =0;
    int quantidade [] = new int[9];
    int codigo[]=new int[9];
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbvisor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        img7 = new javax.swing.JLabel();
        img8 = new javax.swing.JLabel();
        img9 = new javax.swing.JLabel();
        preco1 = new javax.swing.JLabel();
        preco2 = new javax.swing.JLabel();
        preco3 = new javax.swing.JLabel();
        preco4 = new javax.swing.JLabel();
        preco5 = new javax.swing.JLabel();
        preco6 = new javax.swing.JLabel();
        preco7 = new javax.swing.JLabel();
        preco8 = new javax.swing.JLabel();
        preco9 = new javax.swing.JLabel();
        img10 = new javax.swing.JLabel();
        btnsaida = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbtroco = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imglogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(176, 133, 92));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbvisor.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lbvisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbvisor.setText("VISOR");
        lbvisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbvisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 170, 50));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setText("VALOR:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 80, -1));

        jPanel1.setBackground(new java.awt.Color(52, 32, 11));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 50, 40));

        img1.setBackground(new java.awt.Color(255, 255, 255));
        img1.setForeground(new java.awt.Color(255, 255, 255));
        img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 120));

        img2.setForeground(new java.awt.Color(255, 255, 255));
        img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, 120));

        img3.setBackground(new java.awt.Color(255, 255, 255));
        img3.setForeground(new java.awt.Color(255, 255, 255));
        img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 120, 120));

        img4.setForeground(new java.awt.Color(255, 255, 255));
        img4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 120));

        img5.setForeground(new java.awt.Color(255, 255, 255));
        img5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 120, 120));

        img6.setForeground(new java.awt.Color(255, 255, 255));
        img6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(img6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 120, 120));

        img7.setForeground(new java.awt.Color(255, 255, 255));
        img7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(img7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 120, 120));

        img8.setForeground(new java.awt.Color(255, 255, 255));
        img8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(img8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 120, 120));

        img9.setForeground(new java.awt.Color(255, 255, 255));
        img9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(img9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 120, 120));

        preco1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        preco1.setForeground(new java.awt.Color(255, 255, 255));
        preco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preco1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(preco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 20));

        preco2.setForeground(new java.awt.Color(255, 255, 255));
        preco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preco2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(preco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, 20));

        preco3.setForeground(new java.awt.Color(255, 255, 255));
        preco3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preco3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(preco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 120, 20));

        preco4.setForeground(new java.awt.Color(255, 255, 255));
        preco4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preco4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(preco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, 20));

        preco5.setForeground(new java.awt.Color(255, 255, 255));
        preco5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preco5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(preco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 120, 20));

        preco6.setForeground(new java.awt.Color(255, 255, 255));
        preco6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preco6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(preco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 120, 20));

        preco7.setForeground(new java.awt.Color(255, 255, 255));
        preco7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preco7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(preco7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 120, 20));

        preco8.setForeground(new java.awt.Color(255, 255, 255));
        preco8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preco8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(preco8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 120, 20));

        preco9.setForeground(new java.awt.Color(255, 255, 255));
        preco9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preco9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(preco9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 120, 20));

        img10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(img10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 120, 120));

        btnsaida.setBackground(new java.awt.Color(0, 0, 0));
        btnsaida.setForeground(new java.awt.Color(255, 255, 255));
        btnsaida.setText("Saída");
        jPanel1.add(btnsaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 130, 50));

        jLabel7.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, 650));

        txtvalor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtvalor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvalor.setText("R$");
        txtvalor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvalorKeyPressed(evt);
            }
        });
        getContentPane().add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 150, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(102, 51, 0));

        btn1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TROCO: R$");

        lbtroco.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lbtroco.setForeground(new java.awt.Color(255, 255, 255));
        lbtroco.setText("00,00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbtroco, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtroco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 350, 370));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imglogo.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        imglogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imglogo.setText("Coffee Machine");
        jPanel2.add(imglogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 200, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movimento (JLabel img, JLabel destino){
        new Thread(){
            public int x = img.getX(), y = img.getY(); 
        public void run(){
            while(x < destino.getX()){
                x++;
                img.setLocation(x,y);
              
                try{
                    sleep(6);
                }catch(Exception ex){
                    System.out.println("Erro: "+ex);
                }
            }
            
            while(y < destino.getY()){
                y++;
                img.setLocation(x,y);
                
                try{
                sleep(6);
                } catch (Exception ex){
                System.out.println("Erro: "+ex);
                }
            }  
        }
    }.start();
    }
    
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        acao(3,img4);
        movimento(img4,img10);
        quantidade[3]= quantidade[3]-1;
    }//GEN-LAST:event_btn4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       this.getContentPane().setBackground(new java.awt.Color(176,133,92));
    
       int i=0;
       try{
           conn.conectar();
           ResultSet rs = conn.buscacafe();
           while(rs.next()){
               img[i] = Toolkit.getDefaultToolkit().createImage((rs.getBytes("tb01_foto")));
               preco[i]= rs.getDouble("tb01_preco");
               quantidade [i]=rs.getInt("tb01_qtde");
               codigo[i]=rs.getInt("tb01_cod_produto");
               i++;
           }
           conn.desconectar();
       } catch(Exception ex)
        {
            System.out.println("Erro: "+ex);
        }
       
       JLabel[]rotulo = new JLabel[]{preco1,preco2, preco3, preco4,preco5, preco6, preco7, preco8, preco9};
       JLabel[]foto = new JLabel[]{img1,img2,img3,img4,img5,img6,img7,img8,img9};
       JButton botao[] = new JButton[] {btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9};
       for(int j=0;j<9;j++){
           BigDecimal valor = new BigDecimal(preco[j]);
           NumberFormat nf = NumberFormat.getCurrencyInstance();
           rotulo[j].setText(nf.format(valor));
           
           ImageIcon imagem = new ImageIcon(img[j]);
           Image imag = imagem.getImage().getScaledInstance(foto[j].getWidth(), foto[j].getHeight(), Image.SCALE_DEFAULT);
           foto[j].setIcon(new ImageIcon(imag));
           
           if(quantidade[j]==0){
               botao[j].setEnabled(false);
           }
       }
    }//GEN-LAST:event_formWindowOpened

    private void txtvalorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           double dinheiro=Double.parseDouble(txtvalor.getText());
           if(dinheiro==0.05 || dinheiro==0.1 ||dinheiro==0.25 || dinheiro==0.5 || dinheiro==1 || dinheiro==2 || dinheiro==5 || dinheiro==10 || dinheiro==20 || dinheiro==50 || dinheiro==100 || dinheiro==200){
               total+= dinheiro;
               BigDecimal valor = new BigDecimal(total);
               NumberFormat nf = NumberFormat.getCurrencyInstance();
               lbvisor.setText(nf.format(valor));
               txtvalor.setText(null);
           }
       }else{
           txtvalor.setText(null);
    }//GEN-LAST:event_txtvalorKeyPressed
    }
    
    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        acao(0,img1);
        movimento(img1,img10);
        quantidade[0]= quantidade[0]-1;
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        acao(1,img2);
        movimento(img2,img10);
        quantidade[1]= quantidade[1]-1;
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        acao(2,img3);
        movimento(img3,img10);
        quantidade[2]= quantidade[2]-1;
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        acao(4,img5);
        movimento(img5,img10);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
       acao(5,img6);
       movimento(img6,img10);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        acao(6,img7);
        movimento(img7,img10);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        acao(7,img8);
        movimento(img8,img10);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        acao(8,img9);
        movimento(img9,img10);
    }//GEN-LAST:event_btn9ActionPerformed

    
    private void acao(int indice, JLabel campo){
        if(preco[indice]<=total){
            total-= preco[indice];
            lbvisor.setText(null);
            BigDecimal valor = new BigDecimal(total);
            NumberFormat nf=NumberFormat.getCurrencyInstance();
            lbtroco.setText(nf.format(valor));
            campo.setText(null);
            
            //ImageIcon imagem = new ImageIcon(img[indice]);
            //Image imag = imagem.getImage().getScaledInstance(img10.getWidth(), img10.getHeight(), Image.SCALE_DEFAULT);
            //img10.setIcon(new ImageIcon(imag));
            
            String sql = "update tb01_produtos set tb01_qtde = "+quantidade[indice]+" where tb01_cod_produto = "+codigo[indice];
            conn.runSQL(sql);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coffee_Machine_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coffee_Machine_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coffee_Machine_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coffee_Machine_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coffee_Machine_Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnsaida;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img10;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JLabel img8;
    private javax.swing.JLabel img9;
    private javax.swing.JLabel imglogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbtroco;
    private javax.swing.JLabel lbvisor;
    private javax.swing.JLabel preco1;
    private javax.swing.JLabel preco2;
    private javax.swing.JLabel preco3;
    private javax.swing.JLabel preco4;
    private javax.swing.JLabel preco5;
    private javax.swing.JLabel preco6;
    private javax.swing.JLabel preco7;
    private javax.swing.JLabel preco8;
    private javax.swing.JLabel preco9;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
